#!/usr/bin/env ruby

require 'optparse'
require_relative '../lib/safe_update'
options = {}
OptionParser.new do |opts|
  opts.banner = 'Usage: safe_update [options]'

  opts.on('-v', '--version', 'Show version') do |v|
    options[:version] = v
  end

  opts.on('-p', '--push N', 'git push every N commits (so your CI can test changes as you go)') do |p|
    options[:push] = p
  end

  opts.on('-t', '--test COMMAND', "Run tests after each commit. Don't update gems which break tests.") do |test_command|
    options[:test_command] = test_command
  end
end.parse!

if options[:version]
  puts "safe_update version #{SafeUpdate::VERSION}"
else
  SafeUpdate::Updater.new.run(options)
end
